gpw_ind <- c("disasters", "gghed", "stunted", "wasted", "overweight", "mmr",
          "sba", "u5mr", "nmr", "hiv", "tb", "malaria", "hep_b", "ntd", "ncd", 
          "suicide", "substance", "alcohol", "traffic", "famplan", "uhc", "cat_10", "cat_25", 
          "indoor", "ambient", "wash", "poison", "tobacco", "dtp3", "mcv2", "pcv3", "medicines", 
          "doctors", "nurses", "dentists", "pharmacists", "ihr", "devontrack", "femviolence", "informed",
          "water", "sanitation", "handwash", "hhenergy", "pm25", "childviolence",  
          "services_vulnerable", "vaccines_atrisk", "num_polio", "amr_antibiotics", "amr_bloodstream", 
          "hypertension", "transfats", "obese_5_19", "obese_adult")

# Objects to map indicator names to columns
gpw_choices <- c("1.5.1 Natural disasters" = "disasters",
                 "1.a.2 Public health spending" = "gghed",
                 "2.2.1 Stunting under five" = "stunted",
                 "2.2.2 Wasting under five" = "wasted",
                 "2.2.2 Overweight under five" = "overweight",
                 "3.1.1 Maternal mortality" = "mmr",
                 "3.1.2 Skilled birth attendance" = "sba",
                 "3.2.1 Under 5 mortality" = "u5mr",
                 "3.2.2 Neonatal mortality" = "nmr",
                 "3.3.1 HIV incidence" = "hiv",
                 "3.3.2 TB incidence" = "tb",
                 "3.3.3 Malaria incidence" = "malaria",
                 "3.3.4 Hepatitis B incidence" = "hep_b",
                 "3.3.5 NTD numbers" = "ntd",
                 "3.4.1 NCD mortality" = "ncd",
                 "3.4.2 Suicide mortality" = "suicide",
                 "3.5.1 Substance use disorders" = "substance",
                 "3.5.2 Alcohol consumption" = "alcohol",
                 "3.6.1 Road traffic deaths" = "traffic",
                 "3.7.1 Family planning" = "famplan",
                 "3.8.1 UHC service coverage" = "uhc",
                 "3.8.2 Financial protection: 10%" = "cat_10",
                 "3.8.2 Financial protection: 25%" = "cat_25",
                 "3.9.1 Household pollution" = "indoor",
                 "3.9.1 Ambient air pollution" = "ambient",
                 "3.9.2 WASH related mortality" = "wash",
                 "3.9.3 Unintentional poisoning" = "poison",
                 "3.a.1 Tobacco use prevalence" = "tobacco",
                 "3.b.1 DTP3 coverage" = "dtp3",
                 "3.b.1 MCV2 coverage" = "mcv2",
                 "3.b.1 PCV3 coverage" = "pcv3",
                 "3.b.3 Essential medicines" = "medicines",
                 "3.c.1 Doctors density" = "doctors",
                 "3.c.1 Nurses density" = "nurses",
                 "3.c.1 Dentists density" = "dentists",
                 "3.c.1 Pharmacists density" = "pharmacists",
                 "3.d.1 IHR" = "ihr",
                 "4.2.1 Child development" = "devontrack",
                 "5.2.1 Violence against women: partner" = "femviolence",
                 "5.6.1 Informed decisions" = "informed",
                 "6.1.1 Safe drinking water" = "water",
                 "6.2.1a Safe sanitation" = "sanitation",
                 "6.2.1b Handwashing facilities" = "handwash",
                 "7.1.2 Clean fuels access" = "hhenergy",
                 "11.6.2 PM2.5 concentration" = "pm25",
                 "16.2.1 Violence against children" = "childviolence",
                 "Access in fragile settings" = "services_vulnerable",
                 "Vaccines for at-risk population" = "vaccines_atrisk",
                 "Number of Polio cases" = "num_polio",
                 "Access to antibiotics" = "amr_antibiotics",
                 "AMR Bloodstream infections" = "amr_bloodstream",
                 "Hypertension prevalence" = "hypertension",
                 "Regulation on transfats" = "transfats",
                 "Obesity 5-19 years" = "obese_5_19",
                 "Obesity adult" = "obese_adult"
                 )

gpw_column_names <- c("1.5.1 Natural disasters",
                   "1.a.2 Public health spending",
                   "2.2.1 Stunting under five",
                   "2.2.2 Wasting under five",
                   "2.2.2 Overweight under five",
                   "3.1.1 Maternal mortality",
                   "3.1.2 Skilled birth attendance",
                   "3.2.1 Under 5 mortality",
                   "3.2.2 Neonatal mortality",
                   "3.3.1 HIV incidence",
                   "3.3.2 TB incidence",
                   "3.3.3 Malaria incidence",
                   "3.3.4 Hepatitis B incidence",
                   "3.3.5 NTD numbers",
                   "3.4.1 NCD mortality",
                   "3.4.2 Suicide mortality",
                   "3.5.1 Substance use disorders",
                   "3.5.2 Alcohol consumption",
                   "3.6.1 Road traffic deaths",
                   "3.7.1 Family planning",
                   "3.8.1 UHC service coverage",
                   "3.8.2 Financial protection: 10%",
                   "3.8.2 Financial protection: 25%",
                   "3.9.1 Household pollution",
                   "3.9.1 Ambient air pollution",
                   "3.9.2 WASH related mortality",
                   "3.9.3 Unintentional poisoning",
                   "3.a.1 Tobacco use prevalence",
                   "3.b.1 DTP3 coverage",
                   "3.b.1 MCV2 coverage",
                   "3.b.1 PCV3 coverage",
                   "3.b.3 Essential medicines",
                   "3.c.1 Doctors density",
                   "3.c.1 Nurses density",
                   "3.c.1 Dentists density",
                   "3.c.1 Pharmacists density",
                   "3.d.1 IHR",
                   "4.2.1 Child development",
                   "5.2.1 Violence against women: partner",
                   "5.6.1 Informed decisions",
                   "6.1.1 Safe drinking water",
                   "6.2.1a Safe sanitation",
                   "6.2.1b Handwashing facilities",
                   "7.1.2 Clean fuels access",
                   "11.6.2 PM2.5 concentration",
                   "16.2.1 Violence against children",
                   "Access in fragile settings",
                   "Vaccines for at-risk population",
                   "Number of Polio cases",
                   "AMR Bloodstream infections",
                   "Access to antibiotics",
                   "Hypertension prevalence",
                   "Regulation on transfats",
                   "Obesity 5-19 years",
                   "Obesity adult"
                   )

nonsdgs <- c("transfats", "obese_5_19", "obese_adult", "num_polio", "hypertension", "services_vulnerable",
             "vaccines_atrisk", "amr_bloodstream", "amr_antibiotics")

ind_label <- function(ind) {
  switch(ind,
         "disasters" = "Number of deaths attributed to disasters per 100 000 population",
         "gghed" = "Proportion of total government spending on health",
         "stunted" ="Prevalence of stunting among children under 5 years of age",
         "wasted" = "Prevalence of wasting among children under 5 years of age",
         "overweight" = "Prevalence of overweight among children under 5 years of age",
         "mmr" = "Maternal mortality ratio per 100 000 live births",
         "sba" = "Proportion of births attended by skilled health personnel",
         "u5mr" = "Under-5 mortality rate per 1 000 live births",
         "nmr" = "Neonatal mortality rate per 1 000 live births",
         "hiv" = "Number of new HIV infections per 1 000 uninfected population",
         "tb" = "Tuberculosis incidence per 100 000 population",
         "malaria" = "Malaria incidence per 1 000 population",
         "hep_b" = "Hepatitis B incidence per 100 000 population",
         "ntd" = "Number of people requiring interventions against neglected tropical diseases",
         "ncd" = "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease",
         "suicide" = "Suicide mortality rate",
         "substance" = "Coverage of treatment interventions for substance use disorders",
         "alcohol" = "Alcohol per capita consumption (15+ years) within a calendar year in litres of pure alcohol",
         "traffic" = "Death rate due to road traffic injuries",
         "famplan" = "Proportion of women (15 to 49 years) who have their need for family planning satisfied with modern methods",
         "uhc" = "Coverage of essential health services",
         "cat_10" = "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 10%",
         "cat_25" = "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 25%",
         "indoor" = "Mortality rate attributed to household pollution",
         "ambient" = "Mortality rate attributed to ambient air pollution",
         "wash" = "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene",
         "poison" = "Mortality rate attributed to unintentional poisoning",
         "tobacco" = "Age-standardized prevalence of current tobacco use among persons aged 15 years and older",
         "dtp3" = "Proportion of the target population covered by DTP3 vaccinations",
         "mcv2" = "Proportion of the target population covered by MCV2 vaccinations",
         "pcv3" = "Proportion of the target population covered by PCV3 vaccinations",
         "medicines" = "Proportion of health facilities that have a core set of relevant essential medicines available",
         "doctors" = "Density of doctors per 10 000 population",
         "nurses" = "Density of nurses per 10 000 population",
         "dentists" = "Density of dentists per 10 000 population",
         "pharmacists" = "Density of pharmacists per 10 000 population",
         "ihr" = "International Health Regulations (IHR) capacity and health emergency preparedness",
         "devontrack" = "Proportion of children under 5 developmentally on track in health, learning and psychosocial well-being",
         "femviolence" = "Proportion of ever-partnered women aged 15-49 years subjected to intimate partner violence",
         "informed" = "Proportion of women aged 15–49 years who make informed decisions on sexual and reproductive health",
         "water" = "Proportion of population using safely managed drinking water services",
         "sanitation" = "Proportion of population using safely managed sanitation services",
         "handwash" = "Proportion of population using a handwashing facility with soap and water",
         "hhenergy" = "Proportion of population with primary reliance on clean fuels and technology",
         "pm25" = "Annual mean levels of fine particulate matter (PM2.5) in cities",
         "childviolence" = "Proportion of children aged 1-14 years who experienced physical/psychological aggression by caregivers",
         "services_vulnerable" = "Proportion of vulnerable people in fragile settings provided with essential health services",
         "vaccines_atrisk" = "Vaccine coverage of at-risk groups for epidemic or pandemic prone diseases",
         "num_polio" = "Number of cases of poliomyelitis caused by wild poliovirus (WPV)",
         "amr_bloodstream" = "Percentage of bloodstream infections due to antimicrobial resistant organisms",
         "amr_antibiotics" = "Patterns of antibiotic consumption at national level",
         "hypertension" = "Age-standardized prevalence of raised blood pressure among 18+ years",
         "transfats" = "Percentage of people protected by effective regulation on trans fats",
         "obese_5_19" = "Prevalence of obesity among 5-19 years",
         "obese_adult" = "Prevalence of obesity among adults"
        )
}

gpw_choices_full <- c(
  "Number of deaths attributed to disasters per 100 000 population" = "disasters",
  "Proportion of total government spending on health" = "gghed",
  "Prevalence of stunting among children under 5 years of age" = "stunted",
  "Prevalence of wasting among children under 5 years of age" = "wasted",
  "Prevalence of overweight among children under 5 years of age" = "overweight",
  "Maternal mortality ratio per 100 000 live births" = "mmr",
  "Proportion of births attended by skilled health personnel" = "sba",
  "Under-5 mortality rate per 1 000 live births" = "u5mr",
  "Neonatal mortality rate per 1 000 live births" = "nmr",
  "Number of new HIV infections per 1 000 uninfected population" = "hiv",
  "Tuberculosis incidence per 100 000 population" = "tb",
  "Malaria incidence per 1 000 population" = "malaria",
  "Hepatitis B incidence per 100 000 population" = "hep_b",
  "Number of people requiring interventions against neglected tropical diseases" = "ntd",
  "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease" = "ncd",
  "Suicide mortality rate" = "suicide",
  "Coverage of treatment interventions for substance use disorders" = "substance",
  "Alcohol per capita consumption (15+ years) within a calendar year in litres of pure alcohol" = "alcohol",
  "Death rate due to road traffic injuries" = "traffic",
  "Proportion of women (15 to 49 years) who have their need for family planning satisfied with modern methods" = "famplan",
  "Coverage of essential health services" = "uhc",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 10%" = "cat_10",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 25%" = "cat_25",
  "Mortality rate attributed to household pollution" = "indoor",
  "Mortality rate attributed to ambient air pollution" = "ambient",
  "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene" = "wash",
  "Mortality rate attributed to unintentional poisoning" = "poison",
  "Age-standardized prevalence of current tobacco use among persons aged 15 years and older" = "tobacco",
  "Proportion of the target population covered by DTP3 vaccinations" = "dtp3",
  "Proportion of the target population covered by MCV2 vaccinations" = "mcv2",
  "Proportion of the target population covered by PCV3 vaccinations" = "pcv3",
  "Proportion of health facilities that have a core set of relevant essential medicines available" = "medicines",
  "Density of doctors per 10 000 population" = "doctors",
  "Density of nurses per 10 000 population" = "nurses",
  "Density of dentists per 10 000 population" = "dentists",
  "Density of pharmacists per 10 000 population" = "pharmacists",
  "International Health Regulations (IHR) capacity and health emergency preparedness" = "ihr",
  "Proportion of children under 5 developmentally on track in health, learning and psychosocial well-being" = "devontrack",
  "Proportion of ever-partnered women aged 15-49 years subjected to intimate partner violence" = "femviolence",
  "Proportion of women aged 15–49 years who make informed decisions on sexual and reproductive health" = "informed",
  "Proportion of population using safely managed drinking water services" = "water",
  "Proportion of population using safely managed sanitation services" = "sanitation",
  "Proportion of population using a handwashing facility with soap and water" = "handwash",
  "Proportion of population with primary reliance on clean fuels and technology" = "hhenergy",
  "Annual mean levels of fine particulate matter (PM2.5) in cities" = "pm25",
  "Proportion of children aged 1-14 years who experienced physical/psychological aggression by caregivers" = "childviolence",
  "Proportion of vulnerable people in fragile settings provided with essential health services" = "services_vulnerable",
  "Vaccine coverage of at-risk groups for epidemic or pandemic prone diseases" = "vaccines_atrisk",
  "Number of cases of poliomyelitis caused by wild poliovirus (WPV)" = "num_polio",
  "Percentage of bloodstream infections due to antimicrobial resistant organisms" = "amr_bloodstream",
  "Patterns of antibiotic consumption at national level" = "amr_antibiotics",
  "Age-standardized prevalence of raised blood pressure among 18+ years" = "hypertension",
  "Percentage of people protected by effective regulation on trans fats" = "transfats",
  "Prevalence of obesity among 5-19 years" = "obese_5_19",
  "Prevalence of obesity among adults" = "obese_adult"
)

gpw_colnames <- c(
  "Number of deaths attributed to disasters per 100 000 population",
  "Proportion of total government spending on health",
  "Prevalence of stunting among children under 5 years of age",
  "Prevalence of wasting among children under 5 years of age",
  "Prevalence of overweight among children under 5 years of age",
  "Maternal mortality ratio per 100 000 live births",
  "Proportion of births attended by skilled health personnel",
  "Under-5 mortality rate per 1 000 live births",
  "Neonatal mortality rate per 1 000 live births",
  "Number of new HIV infections per 1 000 uninfected population",
  "Tuberculosis incidence per 100 000 population",
  "Malaria incidence per 1 000 population",
  "Hepatitis B incidence per 100 000 population",
  "Number of people requiring interventions against neglected tropical diseases",
  "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease",
  "Suicide mortality rate",
  "Coverage of treatment interventions for substance use disorders",
  "Alcohol per capita consumption (15+ years) within a calendar year in litres of pure alcohol",
  "Death rate due to road traffic injuries",
  "Proportion of women (15 to 49 years) who have their need for family planning satisfied with modern methods",
  "Coverage of essential health services",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 10%",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 25%",
  "Mortality rate attributed to household pollution",
  "Mortality rate attributed to ambient air pollution",
  "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene",
  "Mortality rate attributed to unintentional poisoning",
  "Age-standardized prevalence of current tobacco use among persons aged 15 years and older",
  "Proportion of the target population covered by DTP3 vaccinations",
  "Proportion of the target population covered by MCV2 vaccinations",
  "Proportion of the target population covered by PCV3 vaccinations",
  "Proportion of health facilities that have a core set of relevant essential medicines available",
  "Density of doctors per 10 000 population",
  "Density of nurses per 10 000 population",
  "Density of dentists per 10 000 population",
  "Density of pharmacists per 10 000 population",
  "International Health Regulations (IHR) capacity and health emergency preparedness",
  "Proportion of children under 5 developmentally on track in health, learning and psychosocial well-being",
  "Proportion of ever-partnered women aged 15-49 years subjected to intimate partner violence",
  "Proportion of women aged 15–49 years who make informed decisions on sexual and reproductive health",
  "Proportion of population using safely managed drinking water services",
  "Proportion of population using safely managed sanitation services",
  "Proportion of population using a handwashing facility with soap and water",
  "Proportion of population with primary reliance on clean fuels and technology",
  "Annual mean levels of fine particulate matter (PM2.5) in cities",
  "Proportion of children aged 1-14 years who experienced physical/psychological aggression by caregivers",
  "Proportion of vulnerable people in fragile settings provided with essential health services",
  "Vaccine coverage of at-risk groups for epidemic or pandemic prone diseases",
  "Number of cases of poliomyelitis caused by wild poliovirus (WPV)",
  "Percentage of bloodstream infections due to antimicrobial resistant organisms",
  "Patterns of antibiotic consumption at national level",
  "Age-standardized prevalence of raised blood pressure among 18+ years",
  "Percentage of people protected by effective regulation on trans fats",
  "Prevalence of obesity among 5-19 years",
  "Prevalence of obesity among adults"
)
